### ISSUE TITLE
iOS -> LottieImagesLocation

### ISSUE THREAD

**Issue by YanDevDe** [timbru31/cordova-plugin-lottie-splashscreen#171]
Hello,

I haven't tested it on iOS yet since I'm still waiting to get my Mac device.
But what I saw it following from README.md:

> LottieImagesLocation (String, default path of LottieAnimationLocation). **Android only!** Location of the Lottie images folder specified by the JSON.

Does that mean that animations with containing images are only supported in Android or changing images location is only supported in Android? I was a bit confused here.

Thank you,

YanDev

**Comment by timbru31** [comment]
Hi,

great question! No Lottie animations with images are supported on iOS, too. IIRC, Android will look in the assets folder and not the www folder where the animation is located, unless specified. That's why the property was added for Android. iOS resolves the images relative, so there is no need to configure/support this property.

Is my explanation clear enough or still confusing? 😅

**Comment by YanDevDe** [comment]
Yup! Thank you so much for the answer! 😁
