### ISSUE TITLE
Are you using lottie-splashscreen in production?

### ISSUE THREAD

**Issue by timbru31** [timbru31/cordova-plugin-lottie-splashscreen#73]
If yes, I'd be very happy if you post a link to your app below, so I can check it out  and maybe add a showcase section to the README later (if you are fine with it being added). 👍

**Comment by ansarikhurshid786** [comment]
sure i will do

**Comment by felixbroehl** [comment]
Yes, were using your library in production! Actually really nice library. Keep up the good work.

If you like you can check out our app on the stores or our [website](https://everoo.io/en/).
[Google Play](https://play.google.com/store/apps/details?id=com.glamus.everoo)
[Apple App Store](https://apps.apple.com/us/app/everoo-contacts-up-to-date/id1336001207?mt=8)

**Comment by zraees** [comment]
> Yes, were using your library in production! Actually really nice library. Keep up the good work.
> 
> If you like you can check out our app on the stores or on our [website](https://everoo.io/en/).
> [Google Play](https://play.google.com/store/apps/details?id=com.glamus.everoo)
> [Apple App Store](https://apps.apple.com/us/app/everoo-contacts-up-to-date/id1336001207?mt=8)

Dear,

did you use Cordova or Capacitor ?
I'm using capacitor 2.0.0-beta.1 and andriod app crashed, any clue?

**Comment by felixbroehl** [comment]
Our app is based on Cordova. Furthermore this plugin is only compatible with Cordova.

**Comment by zraees** [comment]
Thanks for the prompt reply, basically I'm newbie and exploring Ionic 5. 
Ionic 5 suggests to use capacitor for all new projects.
what you suggest, should I remove capacitor and start using Cordova?

another thing about this plugin, from the page(Lottie Splash Screen)
https://ionicframework.com/docs/native/lottie-splash-screen
they give command to run this plugin on capacitor
npm install cordova-plugin-lottie-splashscreen
npm install @ionic-native/lottie-splash-screen
ionic cap sync

waiting for your comments

**Comment by felixbroehl** [comment]
It depends on the native features you want to use and which plugins are available for that. With everoo we needed a lot of native features. At the time we're started our project capacitor was not released. So if you need only a few native features and capacitor has all the plugins you need I would suggest to go with capacitor. Currently we're stuck on Cordova because some plugins we're using are not working with Capacitor. (Btw here's a list of known incompatible plugins: https://capacitor.ionicframework.com/docs/cordova/known-incompatible-plugins/) In the future I would definitely go with capacitor.

I don't tested this plugin with capacitor. Maybe it's incompatible and some further work is needed.

**Comment by zraees** [comment]
thanks for you time and reply :)
I'll stick with capacitor.
