### ISSUE TITLE
white screen is shown when splash screen hides in android 

### ISSUE THREAD

**Issue by Haroon6138** [timbru31/cordova-plugin-lottie-splashscreen#89]
First of all, thanks a lot for this wonderful plugin. The issue that i am facing is that after the splash screen hides, only a white screen is shown in android platform, whereas in iOS it's working perfectly, i.e. my app's main page is shown after splash screen hides in iOS. i am using ionic 4.

**Comment by timbru31** [comment]
Thanks a lot for your issue, however the issue template exists for a reason 😉 
It helps me to debug the issue further and to provide a solution much faster. With important information missing, I unfortunately can't help you.

Therefore, please edit this issue accordingly or close and create a new one and make sure to provide all the required information.

**Comment by Divyanshu30** [comment]
Hi I have the same issue is their any way to fix it 
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.6.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 8 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/divyanshu/Library/Android/sdk)
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v8.16.0 (/usr/local/Cellar/node@8/8.16.0/bin/node)
   npm               : 6.4.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.3 Build version 10G8


My config.xml
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="200" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="400" />
    <preference name="LottieAnimationLocation" value="www/lottie/logo.json" />
    <preference name="LottieImagesLocation" value="www/lottie/images" />
    <preference name="LottieFullScreen" value="true" />
    <preference name="LottieLoopAnimation" value="true" />
    <preference name="LottieHideTimeout" value="3500" />

**Comment by timbru31** [comment]
It would really help me to speed up the debugging and fixing if you could provide me an example project with the issue happening @Divyanshu30

**Comment by Divyanshu30** [comment]
@timbru31 here is the sample github repo i have been able to bring down white screen time but the transition is not as smooth as expected.Also, you are doing a fantastic job with this plugin
https://github.com/Divyanshu30/debug-app

**Comment by timbru31** [comment]
Thanks, I'll report back once I've tested your app!

**Comment by timbru31** [comment]
@Divyanshu30 there are quite some issues with the way you are using the plugin:

- This plugin is meant as a replacement for the stock splash screen plugin. It can co-exist with the cordova-plugin-splashscreen in case some plugins depend on it (like the cordova-plugin-ionic does), however it's recommended to disable the stock splash screen with:
  - setting SplashScreenDelay and FadeSplashScreenDuration to 0
- The LottieHideTimeout is in seconds, not milliseconds. Generally I recommend to either hide the Lottie splash screen programatically or with the hide timeout
- You are hiding the splash screen before your home page component is loaded, that's why you see a white screen for some time until Ionic (Angular) loaded the page. To solve this issue move the "hide logic" to some place where you know that some content is displayed (e.g. to the home page component instead, use lifecycle hooks instead, too)

For example we continue the Lottie animation with an animation that kicks off via JS/Angular. The `.hide` method is only called after the animationStart event.

**Comment by Divyanshu30** [comment]
@timbru31  using hide logic after viewInit and timeout together on home page/login screen solves it. Thanks for your help.

Plus I am using same animation as a loader too so i don't have to do write a separate logic for loader. 
Thanks for the plugin
